name: CI Pipeline

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Configure PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -y python3-pip
          pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt install bc  # This may not be necessary unless you're using it in scripts

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Pylint
        run: pip install pylint pytest pydantic
      - name: Lint with Pylint
        run: ./scripts/check_quality_pylint.sh

  format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Black
        run: pip install black
      - name: Format code with Black
        run: ./scripts/format_code.sh

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Pytest
        run: pip install pytest pytest-cov
      - name: Run tests
        run: ./scripts/run_tests.sh

  metrics:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check test coverage
        run: ./scripts/check_test_coverage.sh

  security:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Security analysis with Bandit
        run: ./scripts/check_quality_bandit.sh
